### PR TITLE
New provider MacOS System Vault (Keychain)

### PR DESCRIPTION
**Pull request by vjeantet**
## Related Issues
#126 

## Description
Implement MacOS Provider Sync + Read/Write/Delete secrets.

# Checklist
- [x] Tests
- [x] Documentation
- [x] Linting

### CODE REVIEW

**Comment by vjeantet** [comment]
Hello @jondot Do you have the source of media/providers.png to add a MacOS icon  ?

**Comment by kaplanelad** [comment]
Thanks @vjeantet , thanks for adding support for macOS.

As a security measure, we typically add and update external packages ourselves to prevent any unintended code from being added to the project. However, if you don't mind, would it be possible for me to open a new branch with this upgrade? 
you can test if it work properly and then we will merge it?

This would allow us to test it and ensure that everything is working as expected before we merge it into the main branch.

Once you agree with that, you can fork from my branch and added you Teller code implementation into my branch.

**Comment by vjeantet** [comment]
Hello,

👍 No problem, thanks for the review, ping me when the new branch is available.

I'm curious about the dependency management with "go mod", I thought that the go.sum, go mod tidy and go mod vendor performed with each build/test would neutralize this risk, what is the scenario you want to avoid ?

**Comment by kaplanelad** [comment]
Teller is a highly sensitive security tool, and we aim to ensure that any third-party code we incorporate into it is entirely legitimate. Additionally, we want to avoid the need to redownload code each time we package a new version/developing and more.

Moreover, we aim to provide Teller with offline capabilities, enabling companies to use our tool without requiring a constant internet connection. To achieve this, users need only bring the repository once, and Teller will run seamlessly without internet access.

this is the reason that we store the vendors as part of the source code.

**Comment by kaplanelad** [comment]
@vjeantet can you please share with me which external package do you want me to add?

**Comment by vjeantet** [comment]
Hello, 

github.com/99designs/keyring

This is the new package used in my PR.
- It may indirectly bring new packages which keyring depends on.

**Comment by kaplanelad** [comment]
Hey 
You can open a pull request with the provider implementation into this branch #164

Thanks

**Pull request closed without merging**
