### PR TITLE
ci: Version bump workflows

### PR DESCRIPTION
**Pull request by polarathene**
## Related Issues

N/A

## Description

Overall, version bumps from most releases in March 2022 to those available in August 2023. Does not appear to introduce any breaking changes that would affect the workflows.

- [`goreleaser/goreleaser-action`](https://github.com/goreleaser/goreleaser-action) is at v4 (_the [last v2 release was March 2022](https://github.com/goreleaser/goreleaser-action/releases/tag/v2.9.1)_). Likewise the `gorelease` version has been bumped from `1.7` ([March 2022](https://github.com/goreleaser/goreleaser/releases/tag/v1.7.0)) to `1.20` ([August 2023](https://github.com/goreleaser/goreleaser/releases/tag/v1.20.0)).
- [`golangci/golangci-lint-action`](https://github.com/golangci/golangci-lint-action) is at 3.7, but [`golangci-lint`](https://github.com/golangci/golangci-lint) version is presently `1.54`. The current [`1.45` release is from March 2022](https://github.com/golangci/golangci-lint/releases/tag/v1.45.0).
- `spectralops/spectral-github-action` [v1 was Jan 2022, while Jun 2023 released v4](https://github.com/SpectralOps/spectral-github-action/releases).
- `actions/setup-go` bumped to [`v4`](https://github.com/actions/setup-go/releases/tag/v4.0.0)). Go updated to `1.21` ([Aug 2023](https://go.dev/blog/go1.21)) from `1.18` ([Mar 2022](https://go.dev/blog/go1.18)).
- [`actions/checkout`](https://github.com/actions/checkout) to v4 (Sep 2023).

## Motivation and Context

There was a [minor update in April 2023 to a workflow](https://github.com/tellerops/teller/pull/160), but I felt that the project would benefit from not letting the workflows become stale. At a glance, it doesn't look like there is any breaking changes introduced by any of the dependencies receiving a version bump.

As releases will be built via these workflows, it'd be nice to have them built with a more recent or latest version of Go.

## How Has This Been Tested?

I've not tried running these updated workflows via a fork, but the change should be fairly straight-forward / harmless?

### CODE REVIEW

**Comment by kaplanelad** [comment]
Hi @polarathene ,

Thank you for your pull request! Your contribution is much appreciated. 😄

I noticed that the CI tests have failed for this pull request due of linting upgrade.  can you please take a look?

**Comment by polarathene** [comment]
> can you please take a look?

```
  Running [/home/runner/golangci-lint-1.54.0-linux-amd64/golangci-lint run --out-format=github-actions --timeout 5m0s] in [] ...
  Error: directive `// nolint:dupl` should be written without leading space as `//nolint:dupl` (nolintlint)
  Error: directive `// nolint: gomnd` should be written without leading space as `//nolint: gomnd` (nolintlint)
  Error: directive `// nolint: gomnd` should be written without leading space as `//nolint: gomnd` (nolintlint)
  Error: directive `// nolint: gomnd` should be written without leading space as `//nolint: gomnd` (nolintlint)
  Error: directive `// nolint:dupl` should be written without leading space as `//nolint:dupl` (nolintlint)
  Error: directive `// nolint` should be written without leading space as `//nolint` (nolintlint)
  Error: directive `// nolint` should be written without leading space as `//nolint` (nolintlint)
```

It doesn't say what files, so I'll need to clone the project and find & replace 🤷‍♂️ 

Bit busy right now but might find time for that later today.

**Comment by polarathene** [comment]
> can you please take a look?

Ready for you to run the CI again 👍

**Comment by kaplanelad** [comment]
I noticed that you made modifications to the files within the vendor/* directory. Regrettably, we cannot accept any additions or alterations in this folder due to security concerns. Our objective is to maintain the integrity of the libraries contained therein, as these libraries are sourced from third-party vendors and should not be subject to any changes.

**Comment by polarathene** [comment]
> Regrettably, we cannot accept any additions or alterations in this folder due to security concerns.

I am not a Go dev, you're asking me to make changes beyond the Github Actions workflow files 🤷‍♂️ 

I've reverted the modification to `vendor/`. I don't know your merge policy, so if you need that squashed I can accommodate.

Workflow should be fine to run for now to verify everything else is fine?

**Comment by kaplanelad** [comment]
I'm still seeing changes in vendor folder

**Comment by polarathene** [comment]
> I'm still seeing changes in vendor folder

Yeah, sorry about that. Some already had `//nolint`. Resolved properly.

**Comment by polarathene** [comment]
`goreleaser/goreleaser-action` has a v5 release now (_nothing too important there, mostly a bump in NodeJS to v20 like many other actions are doing recently_), and within a couple days it looks like `goreleaser` will also have a `1.21` release out.

If the workflows pass and everything looks good, you may want to wait just a little longer to cover that as well?

**Comment by kaplanelad** [comment]
@polarathene yes it will be great to fix the linting step

**Comment by polarathene** [comment]
> @polarathene yes it will be great to fix the linting step

You do it.

I contributed the PR with no response for 3 weeks, then addressed the review feedback. Tests passed at the time. It's been over 4 months since then, I am not responsible for that drift.

Versions that are bumped in this PR have likely changed since and should be bumped appropriately. I don't use this project, so feel free to update the PR or close it 🤷‍♂️

**Pull request closed without merging**
