### PR TITLE
Feature/ansible vault

### PR DESCRIPTION
**Pull request by mustafayildirim**
## Related Issues
- #85

## Description
Add ansible_vault provider https://docs.ansible.com/ansible/latest/vault_guide/index.html

## Motivation and Context
There is a missing ansible vault provider and an open issue #85 

## How Has This Been Tested?
Tested local and added mock provider test
ANSIBLE_VAULT_PASSPHRASE=$(cat ~/teller-ansible-vault-pass) go run main.go show --log-level=debug

# Checklist
- [x] Tests
- [x] Documentation
- [x] Linting

### CODE REVIEW

**Comment by kaplanelad** [comment]
Thanks @mustafayildirim , thanks for adding support ansible.

As a security measure, we typically add and update external packages ourselves to prevent any unintended code from being added to the project. However, if you don't mind, would it be possible for me to open a new branch with this upgrade?
you can test if it work properly and then we will merge it?

This would allow us to test it and ensure that everything is working as expected before we merge it into the main branch.

Once you agree with that, you can fork from my branch and added you Teller code implementation into my branch.

**Comment by mustafayildirim** [comment]
Sure @kaplanelad  I understand your external package policy.

Are you going to create a branch?

**Comment by kaplanelad** [comment]
Yes, 
Do you need only this lib? github.com/sosedoff/ansible-vault-go

**Comment by mustafayildirim** [comment]
Hey @kaplanelad yes I only need github.com/sosedoff/ansible-vault-go

**Comment by kaplanelad** [comment]
Hey @mustafayildirim, I noticed in your PR that you used version 0.1.1. Can we import the latest released version, 0.2.0, instead of 0.1.1?

**Comment by mustafayildirim** [comment]
Sure @kaplanelad 0.2.0 version would be better.

**Comment by kaplanelad** [comment]
Hey @mustafayildirim i added the depended pkg in this PR: #167

can you please open your PR into this PR?

thanks!

**Comment by mustafayildirim** [comment]
Hi @kaplanelad I've created a new Pull Request based on your branch #169 
I'll close this PR.

**Pull request closed without merging**
